name: build-mod
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: HostileHumans-1.20.1
          path: build/libs/*.jar
